Repository aimclub/BAMT, pull requests merged in 2023-09, with the labels that each got.

#79 sample fix
  bamt/nodes/conditional_gaussian_node.py
Labels: bug

#80 Release minor fixes
  bamt/builders/evo_builder.py
  bamt/config.py
  bamt/display/display.py
  bamt/networks/__init__.py
  bamt/networks/base.py
  bamt/networks/big_brave_bn.py
  bamt/nodes/conditional_gaussian_node.py
  bamt/nodes/conditional_logit_node.py
  bamt/nodes/discrete_node.py
  bamt/nodes/gaussian_node.py
  bamt/nodes/logit_node.py
  bamt/nodes/schema.py
  bamt/utils/GraphUtils.py
  bamt/utils/MathUtils.py
  bamt/utils/check_utils.py
  bamt/utils/composite_utils/MLUtils.py
  bamt/utils/serialization_utils.py
  pyproject.toml
  tests/test_graph_analyzer.py
  tests/test_networks.py
  tests/test_nodes.py
Labels: bug, documentation, refactoring

#77 New examples & tutorials
  .gitignore
  .readthedocs.yml
  README.rst
  bamt/utils/composite_utils/MLUtils.py
  docs/source/examples/add_ml_models_to_nodes.rst
  docs/source/examples/learn_params_vis.rst
  docs/source/examples/learn_sampling_predict.rst
  docs/source/examples/learn_save.rst
  docs/source/examples/read_structure_and_params.rst
  docs/source/examples/read_structure_param_learning.rst
  docs/source/index.rst
  docs/source/models/bayesiannetworks/base_network.rst
  docs/source/models/bayesiannetworks/composite_bn.rst
  docs/source/models/bayesiannetworks/continuous_bn.rst
  docs/source/models/bayesiannetworks/discrete_bn.rst
  docs/source/models/bayesiannetworks/hybrid_bn.rst
  docs/source/models/bayesiannetworks/large_bn_algs.rst
  docs/source/tutorials/tutorials_gists.rst
  tests/sendingRegressors.py
  tutorials/Nodes.ipynb
  tutorials/Preprocessing.ipynb
  tutorials/example_bigbravebn.ipynb
  tutorials/example_geo.ipynb
  tutorials/example_socio.ipynb
  tutorials/parameters_learning_and_sampling.ipynb
  tutorials/regressor_exp.ipynb
  tutorials/structure_learning.ipynb
Labels: documentation
