Repository aimclub/BAMT, pull requests merged in 2023-03, with the labels that each got.

#40 added codecov badge support
  README.rst
Labels: documentation

#43 Golem compatibility fix
  pyproject.toml
  requirements.txt
Labels: dependencies

#44 Storage fix and regressors feature
  bamt/builders.py
  bamt/networks.py
  tests/test_builders.py
Labels: enhancement
